language: python
python:
 - "3.6"
cache: pip
install: 
 - pip install --upgrade pip
 - sudo apt-get install -qq libegl1-mesa
 - pip install -r requirements.txt
 
script: "python gui/mvm_gui.py fakeESP32"
